name: Scheduled LATEST_STABLE

on:
  schedule:
    - cron: 21 5 9,1,15 * *

jobs:
  call-workflow:
    uses: ./.github/workflows/build.yml
    with:
      version_type: LATEST_STABLE

    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
